// <auto-generated />
using System;
using Jellyfin.Plugin.Podcasts.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jellyfin.Plugin.Podcasts.Database.Migrations;

[DbContext(typeof(PodcastDbContext))]
partial class PodcastDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("Jellyfin.Plugin.Podcasts.Model.AppPassword", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT").HasColumnName("id");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT").HasColumnName("created_at");
            b.Property<string>("Label").IsRequired().HasColumnType("TEXT").HasColumnName("label");
            b.Property<DateTime?>("LastUsedAt").HasColumnType("TEXT").HasColumnName("last_used_at");
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT").HasColumnName("password_hash");
            b.Property<string>("UserId").IsRequired().HasColumnType("TEXT").HasColumnName("user_id");
            b.HasKey("Id");
            b.ToTable("app_passwords");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Podcasts.Model.Episode", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT").HasColumnName("id");
            b.Property<DateTime?>("CachedAt").HasColumnType("TEXT").HasColumnName("cached_at");
            b.Property<long?>("CachedSizeBytes").HasColumnType("INTEGER").HasColumnName("cached_size_bytes");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT").HasColumnName("created_at");
            b.Property<string>("Description").HasColumnType("TEXT").HasColumnName("description");
            b.Property<int?>("DurationSeconds").HasColumnType("INTEGER").HasColumnName("duration_seconds");
            b.Property<string>("EnclosureMime").HasColumnType("TEXT").HasColumnName("enclosure_mime");
            b.Property<long?>("EnclosureLength").HasColumnType("INTEGER").HasColumnName("enclosure_length");
            b.Property<string>("EnclosureUrl").IsRequired().HasColumnType("TEXT").HasColumnName("enclosure_url");
            b.Property<string>("Guid").IsRequired().HasColumnType("TEXT").HasColumnName("guid");
            b.Property<string>("ImageUrl").HasColumnType("TEXT").HasColumnName("image_url");
            b.Property<bool>("IsCached").HasColumnType("INTEGER").HasColumnName("is_cached");
            b.Property<bool>("IsPinned").HasDefaultValue(false).HasColumnType("INTEGER").HasColumnName("is_pinned");
            b.Property<string>("JellyfinItemId").HasColumnType("TEXT").HasColumnName("jellyfin_item_id");
            b.Property<string>("LocalPath").HasColumnType("TEXT").HasColumnName("local_path");
            b.Property<Guid>("PodcastId").HasColumnType("TEXT").HasColumnName("podcast_id");
            b.Property<DateTime?>("PublishedAt").HasColumnType("TEXT").HasColumnName("published_at");
            b.Property<string>("Title").HasColumnType("TEXT").HasColumnName("title");
            b.HasKey("Id");
            b.HasIndex("podcast_id", "guid").IsUnique().HasDatabaseName("IX_episodes_podcast_id_guid");
            b.ToTable("episodes");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Podcasts.Model.Podcast", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT").HasColumnName("id");
            b.Property<string>("Author").HasColumnType("TEXT").HasColumnName("author");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT").HasColumnName("created_at");
            b.Property<string>("Description").HasColumnType("TEXT").HasColumnName("description");
            b.Property<string>("FeedUrl").IsRequired().HasColumnType("TEXT").HasColumnName("feed_url");
            b.Property<string>("FetchError").HasColumnType("TEXT").HasColumnName("fetch_error");
            b.Property<string>("Guid").HasColumnType("TEXT").HasColumnName("guid");
            b.Property<string>("ImageUrl").HasColumnType("TEXT").HasColumnName("image_url");
            b.Property<string>("Language").HasColumnType("TEXT").HasColumnName("language");
            b.Property<DateTime?>("LastFetchedAt").HasColumnType("TEXT").HasColumnName("last_fetched_at");
            b.Property<string>("Title").HasColumnType("TEXT").HasColumnName("title");
            b.HasKey("Id");
            b.HasIndex("feed_url").IsUnique().HasDatabaseName("IX_podcasts_feed_url");
            b.ToTable("podcasts");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Podcasts.Model.UserEpisodeState", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT").HasColumnName("id");
            b.Property<Guid>("EpisodeId").HasColumnType("TEXT").HasColumnName("episode_id");
            b.Property<bool>("IsPlayed").HasColumnType("INTEGER").HasColumnName("is_played");
            b.Property<int>("PositionSeconds").HasColumnType("INTEGER").HasColumnName("position_seconds");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT").HasColumnName("updated_at");
            b.Property<string>("UserId").IsRequired().HasColumnType("TEXT").HasColumnName("user_id");
            b.HasKey("Id");
            b.HasIndex("user_id", "episode_id").IsUnique().HasDatabaseName("IX_user_episode_state_user_id_episode_id");
            b.ToTable("user_episode_state");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Podcasts.Model.UserSubscription", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT").HasColumnName("id");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT").HasColumnName("deleted_at");
            b.Property<bool>("IsSubscribed").HasDefaultValue(true).HasColumnType("INTEGER").HasColumnName("is_subscribed");
            b.Property<Guid>("PodcastId").HasColumnType("TEXT").HasColumnName("podcast_id");
            b.Property<DateTime>("SubscriptionChangedAt").HasColumnType("TEXT").HasColumnName("subscription_changed_at");
            b.Property<string>("UserId").IsRequired().HasColumnType("TEXT").HasColumnName("user_id");
            b.HasKey("Id");
            b.HasIndex("user_id", "podcast_id").IsUnique().HasDatabaseName("IX_user_subscriptions_user_id_podcast_id");
            b.ToTable("user_subscriptions");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Podcasts.Model.Episode", b =>
        {
            b.HasOne("Jellyfin.Plugin.Podcasts.Model.Podcast", "Podcast")
                .WithMany("Episodes")
                .HasForeignKey("PodcastId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Podcast");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Podcasts.Model.UserEpisodeState", b =>
        {
            b.HasOne("Jellyfin.Plugin.Podcasts.Model.Episode", "Episode")
                .WithMany("UserStates")
                .HasForeignKey("EpisodeId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Episode");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Podcasts.Model.UserSubscription", b =>
        {
            b.HasOne("Jellyfin.Plugin.Podcasts.Model.Podcast", "Podcast")
                .WithMany("Subscriptions")
                .HasForeignKey("PodcastId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Podcast");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Podcasts.Model.Podcast", b =>
        {
            b.Navigation("Episodes");
            b.Navigation("Subscriptions");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Podcasts.Model.Episode", b =>
        {
            b.Navigation("UserStates");
        });
#pragma warning restore 612, 618
    }
}
