---
name: "Jellyfin Podcasts"
guid: "22395da6-06bf-4fb0-aa05-2f44881361f8"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Add podcast channel support to Jellyfin"
description: >
  Podcast channel support for Jellyfin.
category: "General"
owner: "codegito"
artifacts:
- "codegito.xyz.podcasts.dll"
changelog: >
  Initial release
