// <auto-generated />
using System;
using Jellyfin.Plugin.Template.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jellyfin.Plugin.Template.Data.Migrations;

[DbContext(typeof(PodcastsDbContext))]
[Migration("20260328000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

        modelBuilder.Entity("Jellyfin.Plugin.Template.Models.PodcastFeed", b =>
        {
            b.Property<string>("Id")
                .HasColumnType("TEXT");

            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("FeedUrl")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("HomePageUrl")
                .HasColumnType("TEXT");

            b.Property<string>("ImageUrl")
                .HasColumnType("TEXT");

            b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Feeds");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Template.Models.UserSubscription", b =>
        {
            b.Property<Guid>("UserId")
                .HasColumnType("TEXT");

            b.Property<string>("FeedId")
                .HasColumnType("TEXT");

            b.Property<DateTime>("DateAdded")
                .HasColumnType("TEXT");

            b.HasKey("UserId", "FeedId");

            b.HasIndex("FeedId");

            b.ToTable("Subscriptions");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Template.Models.UserSubscription", b =>
        {
            b.HasOne("Jellyfin.Plugin.Template.Models.PodcastFeed", "Feed")
                .WithMany("Subscriptions")
                .HasForeignKey("FeedId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Feed");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Template.Models.PodcastFeed", b =>
        {
            b.Navigation("Subscriptions");
        });
#pragma warning restore 612, 618
    }
}
