// <auto-generated />
using System;
using Jellyfin.Plugin.Template.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jellyfin.Plugin.Template.Data.Migrations;

[DbContext(typeof(PodcastsDbContext))]
[Migration("20260328000002_ApiSupport")]
partial class ApiSupport
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

        modelBuilder.Entity("Jellyfin.Plugin.Template.Models.AppPassword", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("TEXT");

            b.Property<string>("Kind")
                .IsRequired()
                .HasDefaultValue("openpodcastapi")
                .HasColumnType("TEXT");

            b.Property<string>("Label")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<DateTime?>("LastUsedAt")
                .HasColumnType("TEXT");

            b.Property<string>("TokenHash")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<Guid>("UserId")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("AppPasswords");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Template.Models.DeletionRequest", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasAnnotation("Sqlite:Autoincrement", true);

            b.Property<DateTime?>("CompletedAt")
                .HasColumnType("TEXT");

            b.Property<string>("FeedId")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("Message")
                .HasColumnType("TEXT");

            b.Property<DateTime>("RequestedAt")
                .HasColumnType("TEXT");

            b.Property<string>("Status")
                .IsRequired()
                .HasDefaultValue("PENDING")
                .HasColumnType("TEXT");

            b.Property<Guid>("UserId")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("DeletionRequests");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Template.Models.PodcastFeed", b =>
        {
            b.Property<string>("Id")
                .HasColumnType("TEXT");

            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("FeedUrl")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("HomePageUrl")
                .HasColumnType("TEXT");

            b.Property<string>("ImageUrl")
                .HasColumnType("TEXT");

            b.Property<string>("MediaType")
                .IsRequired()
                .HasDefaultValue("Audio")
                .HasColumnType("TEXT");

            b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Feeds");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Template.Models.UserSubscription", b =>
        {
            b.Property<Guid>("UserId")
                .HasColumnType("TEXT");

            b.Property<string>("FeedId")
                .HasColumnType("TEXT");

            b.Property<DateTime>("DateAdded")
                .HasColumnType("TEXT");

            b.Property<DateTime?>("Deleted")
                .HasColumnType("TEXT");

            b.Property<DateTime?>("GuidChanged")
                .HasColumnType("TEXT");

            b.Property<bool>("IsSubscribed")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(true);

            b.Property<string>("NewGuid")
                .HasColumnType("TEXT");

            b.Property<DateTime?>("SubscriptionChanged")
                .HasColumnType("TEXT");

            b.HasKey("UserId", "FeedId");

            b.HasIndex("FeedId");

            b.ToTable("Subscriptions");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Template.Models.UserSubscription", b =>
        {
            b.HasOne("Jellyfin.Plugin.Template.Models.PodcastFeed", "Feed")
                .WithMany("Subscriptions")
                .HasForeignKey("FeedId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Feed");
        });

        modelBuilder.Entity("Jellyfin.Plugin.Template.Models.PodcastFeed", b =>
        {
            b.Navigation("Subscriptions");
        });
#pragma warning restore 612, 618
    }
}
